/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)


// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END



/*********************************************************************
*
*       _cbWindow
*
* Function description
*   The callback moves the edit-fiels when a notification message was send.
*/
//清屏
/*
static void _cbWindow(WM_MESSAGE * pMsg) {
	WM_SCROLL_STATE stScrollState;
	int             x;
	int             y;
 
	switch (pMsg->MsgId) {
	case WM_NOTIFY_PARENT:
 
		break;
	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();
		break;
	default:
		WM_DefaultProc(pMsg);
	}
}
*/
#define ID_WINDOW_0 100
#define ID_WINDOW_1 101
WM_HWIN hWin1;
WM_HWIN hWin2;
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowMain(void);
WM_HWIN CreateWindowMain(void) {
  //WM_HWIN hWin;
  //hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  hWin1 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), Window0_Callback, WM_HBKWIN, 0, 0);	
  hWin2 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), Window1_Callback, WM_HBKWIN, 0, 0);
  // Initially show Dialog1 and hide Dialog2
  WM_ShowWindow(hWin1);  //显示主页1
  WM_HideWindow(hWin2);	//隐藏主页2
  return hWin1;
  //WM_HWIN g_stNetSetPageHWin;	
  //g_stNetSetPageHWin = WM_CreateWindow(0, 0, 800, 480, WM_CF_SHOW, _cbWindow, 0);  //WM_CF_SHOW窗口创建后立即显示 0窗口的唯一标识符
 
  //WM_HWIN g_stNetSetPageHWinChild = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_stNetSetPageHWin, 0, 0);
  //return g_stNetSetPageHWin;
	
  //hWin = WM_CreateWindowAsChild(0, 0, 800, 480, WM_HBKWIN, ID_WINDOW_0, Window0_Callback, 0);
  //WM_CreateWindowAsChild(800, 0, 800, 480, WM_HBKWIN, ID_WINDOW_1, &Window1_Callback, 0);
  //return hWin;

  //WM_HWIN hWin;
  //hWin = WM_CreateWindow(0, 0, 800, 480, WM_CF_SHOW, Window0_Callback, ID_WINDOW_0);
  //WM_HWIN g_stNetSetPageHWin;	
  //g_stNetSetPageHWin = WM_CreateWindow(800, 0, 800, 480, WM_CF_SHOW, Window1_Callback, ID_WINDOW_1);  //WM_CF_SHOW窗口创建后立即显示 0窗口的唯一标识符	
  return hWin; 	
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
