/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)
#define ID_BUTTON_5    (GUI_ID_USER + 0x07)
#define ID_BUTTON_6    (GUI_ID_USER + 0x08)
#define ID_BUTTON_7    (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmLightingMasterOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmSpotlightOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmTemperature;
extern GUI_CONST_STORAGE GUI_BITMAP bmHumidity;
extern GUI_CONST_STORAGE GUI_BITMAP bmBrightnesss;
extern GUI_CONST_STORAGE GUI_BITMAP bmFanOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmAlarm;
extern GUI_CONST_STORAGE GUI_BITMAP bmTurnOff;
extern GUI_CONST_STORAGE GUI_BITMAP bmblue;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 4 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 40, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 230, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 420, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 610, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 40, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 230, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_6, 420, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_7, 610, 270, 150, 150, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    // USER START (Optionally insert additional code for further widget initialization)
    // 根据空间ID,获取空间句柄
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_LightingMaster'
	//
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Spotlight'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmSpotlightOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Temperature'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTemperature);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Humidity'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 设置按钮未按下时，显示温度图片
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmHumidity);
	// 设置按键按下时，显示蓝色图片
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Brightnesss'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmBrightnesss);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Fan'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmFanOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
		//
	// Initialization of 'Button_Alarm'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmAlarm);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
    //
	// Initialization of 'Button_TurnOff'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTurnOff);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		CreateLightingMaster(); // 创建LightingMaster界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
        CreateSpotlight(); // 创建Spotlight界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
        CreateTemperature(); // 创建Temperature界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
        CreateHumidity(); // 创建Humidity界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
        CreateBrightnesss(); // 创建Brightnesss界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		CreateFan(); // 创建Fan界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
        CreateAlarm(); // 创建Alarm界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowMain(void);
WM_HWIN CreateWindowMain(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
