/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
#include "FreeRTOS.h"
#include "task.h"
#include "usart.h"
#include "WM.h"
#include <stdlib.h>  //abs

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)
#define ID_BUTTON_5    (GUI_ID_USER + 0x07)
#define ID_BUTTON_6    (GUI_ID_USER + 0x08)
#define ID_BUTTON_7    (GUI_ID_USER + 0x09)
#define ID_TEXT_0  (GUI_ID_USER + 0x0a)
#define ID_TEXT_1  (GUI_ID_USER + 0x0b)
#define ID_TEXT_2  (GUI_ID_USER + 0x0c)
#define ID_TEXT_3  (GUI_ID_USER + 0x0d)
#define ID_TEXT_4  (GUI_ID_USER + 0x0e)
#define ID_TEXT_5  (GUI_ID_USER + 0x0f)
#define ID_TEXT_6  (GUI_ID_USER + 0x10)
#define ID_TEXT_7  (GUI_ID_USER + 0x11)

#define ID_BUTTON_8        (GUI_ID_USER + 0x12)

// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmLightingMasterOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmSpotlightOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmTemperature;
extern GUI_CONST_STORAGE GUI_BITMAP bmHumidity;
extern GUI_CONST_STORAGE GUI_BITMAP bmBrightnesss;
extern GUI_CONST_STORAGE GUI_BITMAP bmFanOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmAlarm;
extern GUI_CONST_STORAGE GUI_BITMAP bmTurnOff;
extern GUI_CONST_STORAGE GUI_BITMAP bmblue;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
extern int currentDialog;  //mainTask.c
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
/*
static int startX, startY;
static int first_pressed = 1;
static int endX, endY;
*/
/*
static int startX = 0;
static int startY = 0;
static int lastX = 0;
static int lastY = 0;
static int press = 1;
static int pressed = 0;

static TaskHandle_t xReadTouchScreenTaskHandle;
static void ReadTouchScreen(void *pvParameters){
	GUI_PID_STATE State;
	//获取触摸笔状态值
	GUI_TOUCH_GetState(&State);
	if(State.Pressed){
		if(press){
		  startX = State.x;
		  startY = State.y;
		  printf("start x: %d, start y: %d\n", startX, startY);
		  press = 0;
		}
		lastX = State.x;
		lastY = State.y;
		//printf("end x: %d, end y: %d\n", lastX, lastY);
		pressed = 1;
	}else{
		if(pressed){
			press = 1;
			printf("end x: %d, end y: %d\n", lastX, lastY);
			// 计算滑动距离
			int deltaX = lastX - startX;
			int deltaY = lastY - startY;
			printf("deltaX: %d, deltaY: %d\n", deltaX, deltaY);
		
			printf("abs(deltaX): %d., abs(deltaY): %d\n", abs(deltaX), abs(deltaY));
			if (abs(deltaX) > abs(deltaY)) { // 水平滑动
				printf("Horizontal\n");
				if (deltaX > 50) { // 触摸从右向左，窗口向左滑动
					if (currentDialog == 2) {
						printf("left\n");
						WM_HideWindow(hWin2);
						WM_ShowWindow(hWin1);
						currentDialog = 1;
					}
				}else if (deltaX < -50) { // 触摸从左向右，窗口向右滑动
					if (currentDialog == 1) {
						printf("right\n");
						WM_HideWindow(hWin1);
						WM_ShowWindow(hWin2);
						currentDialog = 2;
					}
				}
			}
	  }
	  pressed = 0;
	}
}
static void DeleteUpdateTask(void) {
    if (xReadTouchScreenTaskHandle != NULL) {
        vTaskDelete(xReadTouchScreenTaskHandle);
        xReadTouchScreenTaskHandle = NULL;
    }
}
*/
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 4 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 40, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 230, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 420, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 610, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 40, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 230, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_6, 420, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_7, 610, 270, 150, 150, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
      { TEXT_CreateIndirect, "Text", ID_TEXT_0, 40, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_1, 230, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_2, 420, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_3, 610, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_4, 40, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_5, 230, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_6, 420, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_7, 610, 420, 150, 32, 0, 0x64, 0 },
	  { BUTTON_CreateIndirect, "Next", ID_BUTTON_8, 734, 443, 66, 37, 0, 0x0, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	//printf("pMsg");
	/*
	//只要屏幕有触摸，事件就会通过_cbDialog来处理
	cur_brightness = lcd_get_backlight_by_pwm(); //获取当前背光值
	//只要屏幕背光亮度是0，就不处理任何事件，而是将屏幕背光设置到息屏之前的值
	if(0 == cur_brightness && DefaultProc){
		lcd_set_backlight_by_pwm(last_brightness); // 设置占空比为息屏之前的值，开启背光
		printf("pMsg backlight on");
		return ;  //不处理任何按钮的响应
	}
	*/
  // USER END

  switch (pMsg->MsgId) {
  /*
  case WM_PAINT:  //每次窗口需要重绘时都会触发
	  hItem = pMsg->hWin;
	  WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
	  break;
  */
	 //检测屏幕滑动并切换界面
	  /*
	 case WM_TOUCH:
		//printf("pMsg->Data.v:%d\n", pMsg->Data.v);
		switch (pMsg->Data.v) {
			case 1744965552:  //触摸
				if(first_pressed){
					//printf("pressed\n");
					// 记录触摸开始位置
					startX = ((int*)pMsg->Data.p)[0];
					startY = ((int*)pMsg->Data.p)[1];
					first_pressed = 0;
					//printf("startX: %d, startY: %d", startX, startY);
				}
				endX = ((int*)pMsg->Data.p)[0];
				endY = ((int*)pMsg->Data.p)[1];
				break;
			case 0:  //释放，获取的XY坐标有问题
				//printf("released\n");
				//int endX = ((int*)pMsg->Data.p)[0];
				//int endY = ((int*)pMsg->Data.p)[1];
				//printf("endX: %d, endY: %d\n", endX, endY);

				// 计算滑动距离
				int deltaX = endX - startX;
				int deltaY = endY - startY;
				//printf("deltaX: %d, deltaY: %d\n", deltaX, deltaY);
			
			    //printf("abs(deltaX): %d., abs(deltaY): %d\n", abs(deltaX), abs(deltaY));
				if (abs(deltaX) > abs(deltaY)) { // 水平滑动
					if (deltaX > 50) { // 向右滑动
						if (currentDialog == 1) {
							//printf("right\n");
							WM_HideWindow(hWin1);
							WM_ShowWindow(hWin2);
							currentDialog = 2;
							first_pressed = 1;
							return;
						}
					}
				}
				first_pressed = 1;
				break;
		}
		break;
		*/
  case WM_INIT_DIALOG:  //用于初始化窗口，设置初始属性和状态。仅在窗口第一次创建时触发一次。
		//DefaultProc = 0;
		//printf("WM_INIT_DIALOG\n");
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    // USER START (Optionally insert additional code for further widget initialization)
	//
    // Initialization of 'Text0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "LightingMaster");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "主灯");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //WM_InvalidateWindow(hItem);  // 强制刷新窗口
    //
    // Initialization of 'Text1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "SpotLight");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "射灯");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "temp");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "温度");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "humidity");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "湿度");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
            //
    // Initialization of 'Text4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "brightness");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "亮度");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "Fan");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "风扇");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
            //
    // Initialization of 'Text6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "Alarm");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "警报");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "TurnOff");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "背光");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		
		
    // 根据空间ID,获取空间句柄
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_LightingMaster'
	//
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Spotlight'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmSpotlightOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Temperature'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTemperature);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Humidity'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // 设置按钮未按下时，显示温度图片
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmHumidity);
	// 设置按键按下时，显示蓝色图片
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Brightnesss'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmBrightnesss);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Fan'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmFanOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
		//
	// Initialization of 'Button_Alarm'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmAlarm);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
    //
	// Initialization of 'Button_TurnOff'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTurnOff);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	
	//开启一个任务用于获取屏幕滑动状态
	// 创建获取屏幕滑动状态的任务
    //xTaskCreate(ReadTouchScreen, "getPositationTask", 256, 0, tskIDLE_PRIORITY + 1, &xReadTouchScreenTaskHandle);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
		//printf("WM_NOTIFY_PARENT\n");
		//DefaultProc = !DefaultProc;
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	    currentDialog = 0;  //已经不是主页了，防止滑动检测误判
		CreateLightingMaster(); // 创建LightingMaster界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateSpotlight(); // 创建Spotlight界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateTemperature(); // 创建Temperature界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateHumidity(); // 创建Humidity界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateBrightnesss(); // 创建Brightnesss界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
		CreateFan(); // 创建Fan界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateAlarm(); // 创建Alarm界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
		currentDialog = 0;  //已经不是主页了，防止滑动检测误判
        CreateTurnOff();

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		printf("window flip left\n");
		WM_HideWindow(hWin1);
		WM_ShowWindow(hWin2);
		currentDialog = 2;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;	  
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_DELETE:
	  //销毁任务
	  //DeleteUpdateTask();
	  break;
  // USER END
  default:
		//printf("default\n");
		//DefaultProc = 1;
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow0Main(void);
WM_HWIN CreateWindow0Main(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void Window0_Callback(WM_MESSAGE * pMsg){
    _cbDialog(pMsg);
}
// USER END

/*************************** End of file ****************************/
