/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
#include "FreeRTOS.h"
#include "task.h"
#include "usart.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)
#define ID_BUTTON_5    (GUI_ID_USER + 0x07)
#define ID_BUTTON_6    (GUI_ID_USER + 0x08)
#define ID_BUTTON_7    (GUI_ID_USER + 0x09)
#define ID_TEXT_0  (GUI_ID_USER + 0x0a)
#define ID_TEXT_1  (GUI_ID_USER + 0x0b)
#define ID_TEXT_2  (GUI_ID_USER + 0x0c)
#define ID_TEXT_3  (GUI_ID_USER + 0x0d)
#define ID_TEXT_4  (GUI_ID_USER + 0x0e)
#define ID_TEXT_5  (GUI_ID_USER + 0x0f)
#define ID_TEXT_6  (GUI_ID_USER + 0x10)
#define ID_TEXT_7  (GUI_ID_USER + 0x11)

// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmLightingMasterOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmSpotlightOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmTemperature;
extern GUI_CONST_STORAGE GUI_BITMAP bmHumidity;
extern GUI_CONST_STORAGE GUI_BITMAP bmBrightnesss;
extern GUI_CONST_STORAGE GUI_BITMAP bmFanOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmAlarm;
extern GUI_CONST_STORAGE GUI_BITMAP bmTurnOff;
extern GUI_CONST_STORAGE GUI_BITMAP bmblue;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 4 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 40, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 230, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 420, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 610, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 40, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 230, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_6, 420, 270, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_7, 610, 270, 150, 150, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
      { TEXT_CreateIndirect, "Text", ID_TEXT_0, 40, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_1, 230, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_2, 420, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_3, 610, 210, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_4, 40, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_5, 230, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_6, 420, 420, 150, 32, 0, 0x64, 0 },
      { TEXT_CreateIndirect, "Text", ID_TEXT_7, 610, 420, 150, 32, 0, 0x64, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	//printf("pMsg");
	/*
	//åªè¦å±å¹•æœ‰è§¦æ‘¸ï¼Œäº‹ä»¶å°±ä¼šé€šè¿‡_cbDialogæ¥å¤„ç†
	cur_brightness = lcd_get_backlight_by_pwm(); //èŽ·å–å½“å‰èƒŒå…‰å€¼
	//åªè¦å±å¹•èƒŒå…‰äº®åº¦æ˜¯0ï¼Œå°±ä¸å¤„ç†ä»»ä½•äº‹ä»¶ï¼Œè€Œæ˜¯å°†å±å¹•èƒŒå…‰è®¾ç½®åˆ°æ¯å±ä¹‹å‰çš„å€¼
	if(0 == cur_brightness && DefaultProc){
		lcd_set_backlight_by_pwm(last_brightness); // è®¾ç½®å ç©ºæ¯”ä¸ºæ¯å±ä¹‹å‰çš„å€¼ï¼Œå¼€å¯èƒŒå…‰
		printf("pMsg backlight on");
		return ;  //ä¸å¤„ç†ä»»ä½•æŒ‰é’®çš„å“åº”
	}
	*/
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		//DefaultProc = 0;
		//printf("WM_INIT_DIALOG\n");
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    // USER START (Optionally insert additional code for further widget initialization)
	//
    // Initialization of 'Text0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "LightingMaster");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "ä¸»ç¯");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //WM_InvalidateWindow(hItem);  // å¼ºåˆ¶åˆ·æ–°çª—å£
    //
    // Initialization of 'Text1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "SpotLight");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "å°„ç¯");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "temp");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "æ¸©åº¦");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "humidity");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "æ¹¿åº¦");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
            //
    // Initialization of 'Text4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "brightness");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "äº®åº¦");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "Fan");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "é£Žæ‰‡");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
            //
    // Initialization of 'Text6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "Alarm");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "è­¦æŠ¥");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "TurnOff");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // è®¾ç½®å­—ä½“
    TEXT_SetText(hItem, "èƒŒå…‰");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // è®¾ç½®æ–‡æœ¬å¯¹é½æ–¹å¼ï¼ˆå¯é€‰ï¼‰
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		
		
    // ¸ù¾Ý¿Õ¼äID,»ñÈ¡¿Õ¼ä¾ä±ú
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_LightingMaster'
	//
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Spotlight'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmSpotlightOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Temperature'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTemperature);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Humidity'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    // ÉèÖÃ°´Å¥Î´°´ÏÂÊ±£¬ÏÔÊ¾ÎÂ¶ÈÍ¼Æ¬
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmHumidity);
	// ÉèÖÃ°´¼ü°´ÏÂÊ±£¬ÏÔÊ¾À¶É«Í¼Æ¬
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Brightnesss'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmBrightnesss);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
	//
	// Initialization of 'Button_Fan'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmFanOn);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
		//
	// Initialization of 'Button_Alarm'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmAlarm);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
    //
	// Initialization of 'Button_TurnOff'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTurnOff);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
		//printf("WM_NOTIFY_PARENT\n");
		//DefaultProc = !DefaultProc;
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
		CreateLightingMaster(); // ´´½¨LightingMaster½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
        CreateSpotlight(); // ´´½¨Spotlight½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
        CreateTemperature(); // ´´½¨Temperature½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
        CreateHumidity(); // ´´½¨Humidity½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
        CreateBrightnesss(); // ´´½¨Brightnesss½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
		CreateFan(); // ´´½¨Fan½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);  //½áÊø¶Ô»°¿ò
        CreateAlarm(); // ´´½¨Alarm½çÃæ£¬µ÷ÓÃÆäËü½çÃæµÄCreate·½·¨
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin, 0);  //Þ¡Ë¸×”Û°à ²
        CreateTurnOff();

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
		//printf("default\n");
		//DefaultProc = 1;
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowMain(void);
WM_HWIN CreateWindowMain(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
