/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

#include "include_dlg.h"
#include "FreeRTOS.h"
#include "task.h"
#include "usart.h"
#include <stdlib.h>  //abs

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_0  (GUI_ID_USER + 0x0a)
#define ID_TEXT_1  (GUI_ID_USER + 0x0b)


// USER START (Optionally insert additional defines)
//LoRaOn
extern GUI_CONST_STORAGE GUI_BITMAP bmLoRaOn;
//Wifi
extern GUI_CONST_STORAGE GUI_BITMAP bmWifi;
//LoRaOff
extern GUI_CONST_STORAGE GUI_BITMAP bmLoRaOff;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
extern GUI_CONST_STORAGE GUI_BITMAP bmblue;
//extern uint8_t main0Page;
//extern uint8_t main1Page;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
/*
static int startX, startY;
static int first_pressed = 1;
*/
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 2, 1, 800, 480, 0, 0x0, 4 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 40, 60, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 230, 60, 150, 150, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 40, 210, 150, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 230, 210, 150, 32, 0, 0x64, 0 },  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	  //检测屏幕滑动并切换界面
	  /*
	 case WM_TOUCH:
		printf("pMsg->Data.v:%d\n", pMsg->Data.v);
		switch (pMsg->Data.v) {
			case 1744965552:
				if(first_pressed){
					printf("pressed\n");
					// 记录触摸开始位置
					startX = ((int*)pMsg->Data.p)[0];
					startY = ((int*)pMsg->Data.p)[1];
					first_pressed = 0;
					printf("startX: %d, startY: %d\n", startX, startY);
				}
				break;
			case 0:
				printf("released\n");
				int endX = ((int*)pMsg->Data.p)[0];
				int endY = ((int*)pMsg->Data.p)[1];
				printf("endX: %d, endY: %d\n", endX, endY);

				// 计算滑动距离
				int deltaX = endX - startX;
				int deltaY = endY - startY;
				printf("deltaX: %d, deltaY: %d\n", deltaX, deltaY);
			
			    printf("abs(deltaX): %d., abs(deltaY): %d\n", abs(deltaX), abs(deltaY));
				if (abs(deltaX) > abs(deltaY)) { // 水平滑动
					printf("Horizontal\n");
					if (deltaX < -50) { // 向左滑动
						if (currentDialog == 2) {
							printf("left\n");
							WM_HideWindow(hWin2);
							WM_ShowWindow(hWin1);
							currentDialog = 1;
							first_pressed = 1;
							return;
						}
					}
				}
				first_pressed = 1;
				break;
		}
		break;
	  */
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'Window'
		//
		hItem = pMsg->hWin;
		WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
		// USER START (Optionally insert additional code for further widget initialization)
		//
		// Initialization of 'Text0'
		//
  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		//TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
		//TEXT_SetText(hItem, "LightingMaster");

		TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
		TEXT_SetText(hItem, "门锁");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//WM_InvalidateWindow(hItem);  // 强制刷新窗口
		//
		// Initialization of 'Text1'
		//

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		//TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
		//TEXT_SetText(hItem, "SpotLight");
		TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
		TEXT_SetText(hItem, "网络");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		
		// 根据空间ID,获取空间句柄
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		//
		// Initialization of 'Button_LightingMaster'
		//
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLoRaOn);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
		//
		// Initialization of 'Button_Spotlight'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmWifi);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmblue);
		//main0Page = 0;
		//main1Page = 1;
		// USER END
		break;
	  case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		case ID_BUTTON_0: // Notifications sent by 'Button'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	        currentDialog = 0;  //已经不是主页了，防止滑动检测误判
		    CreateMagnetismLock(); // 创建MagnetismLock界面，调用其它界面的Create方法
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
		    //添加网络界面程序就奔溃，单独使用这个界面没有问题，说明系统资源不够了
		    //因此只添加一个网络信息展示界面
		  	GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	        currentDialog = 0;  //已经不是主页了，防止滑动检测误判
		    CreateNetworkInfoWindow(); // 创建NetworkWindow界面，调用其它界面的Create方法
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
		break;
	  // USER START (Optionally insert additional message handling)
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow1Main(void);
WM_HWIN CreateWindow1Main(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void Window1_Callback(WM_MESSAGE * pMsg){
    _cbDialog(pMsg);
}
// USER END

/*************************** End of file ****************************/
