/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_SLIDER_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0     (GUI_ID_USER + 0x02)
#define ID_TEXT_0     (GUI_ID_USER + 0x03)
#define ID_TEXT_1     (GUI_ID_USER + 0x04)
#define ID_TEXT_2     (GUI_ID_USER + 0x5)
#define ID_TEXT_3     (GUI_ID_USER + 0x6)
#define ID_BUTTON_1     (GUI_ID_USER + 7)
#define ID_TEXT_4     (GUI_ID_USER + 8)

// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmTurnOff;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPage;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPagePressed;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;

static int status = 1;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "TurnOff", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 50, 100, 700, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 500, 200, 150, 150, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "L", ID_TEXT_0, 20, 105, 80, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "H", ID_TEXT_1, 760, 105, 80, 32, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 0, 800, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 0, 42, 800, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 150, 200, 150, 150, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 150, 320, 150, 32, 0, 0x64, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'TurnOff'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    //
    // Initialization of 'L'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "L");
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'H'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    TEXT_SetText(hItem, "H");
    // USER START (Optionally insert additional code for further widget initialization)
    // ���ݿռ�ID,��ȡ�ռ���
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_LightingMaster'
	//
    BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmMainPage);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmMainPagePressed);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_Fontfont);  // ��������
    TEXT_SetText(hItem, "����");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // �����ı����뷽ʽ����ѡ��
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);  // ��������
    TEXT_SetText(hItem, "255");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // �����ı����뷽ʽ����ѡ��
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmTurnOff);
    BUTTON_SetFocusable();

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);  // ��������
    TEXT_SetFont(hItem, &GUI_Fontfont);  // ��������
    TEXT_SetText(hItem, "Ϣ��");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // �����ı����뷽ʽ����ѡ��

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetFocusColor(hItem, 0x00043F97);
    SLIDER_SetNumTicks(hItem, 100);
    SLIDER_SetRange(hItem, 0, 100); //[5:255]
    SLIDER_SetValue(hItem, 100);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //������ҳ
        GUI_EndDialog(pMsg->hWin, 0);  //�����Ի���
        CreateWindowMain(); // ����WindowMain���棬�������������Create����
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

    case ID_BUTTON_1: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		status = !status;
        if(status){
            //backlight on

        }else{
			//backlight off

        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTurnOff
*/
WM_HWIN CreateTurnOff(void);
WM_HWIN CreateTurnOff(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
