/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
#include "main.h"  //LED_Groups LED_pins
#include "gpio.h"  //HAL_GPIO_WritePin
//#include "esp8266_web.h"  //ESP8266_sendBroadcastCmd
#include "esp8266_web_DMA.h"  //ESP8266_sendBroadcastCmd
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_TEXT_0        (GUI_ID_USER + 0x01)
#define ID_BUTTON_0        (GUI_ID_USER + 0x02)
#define ID_BUTTON_1        (GUI_ID_USER + 0x03)
#define ID_SLIDER_0    (GUI_ID_USER + 0x04)
#define ID_SLIDER_1    (GUI_ID_USER + 0x05)
#define ID_SLIDER_2    (GUI_ID_USER + 0x06)
#define ID_TEXT_1    (GUI_ID_USER + 0x07)
#define ID_TEXT_2    (GUI_ID_USER + 0x08)
#define ID_TEXT_3    (GUI_ID_USER + 0x09)


// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_BITMAP bmLightingMasterOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmLightingMasterOff;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPage;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPagePressed;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
static int status = 0;

uint16_t MasterLight_R_slider = 0;  //保存当前R滑块值
uint16_t MasterLight_G_slider = 0;  //保存当前G滑块值
uint16_t MasterLight_B_slider = 0;  //保存当前B滑块值
static char cmd[35] = {0};

uint8_t MasterLight_RGBchanged = 0;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "LightingMaster", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 800, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 500, 200, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 150, 200, 150, 150, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 170, 50, 480, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 170, 100, 480, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_2, 170, 150, 480, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "R", ID_TEXT_1, 150, 52, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "G", ID_TEXT_2, 150, 102, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "B", ID_TEXT_3, 150, 152, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
#include "FreeRTOS.h"
#include "task.h"
static TaskHandle_t xUpdateTaskHandle;
static void UpdateTextTask(void *pvParameters) {
    //WM_HWIN hItem = (WM_HWIN)pvParameters;
	WM_HWIN HWIN = (WM_HWIN)pvParameters;
	WM_HWIN hItem;
    while (1) {
		if(MasterLight_RGBchanged){  //只有在灯光控制开关和RBG滑块滑动后才设置并强制刷新控件
			//web方式开关灯需要更新滑块
			hItem = WM_GetDialogItem(HWIN, ID_SLIDER_0);
			SLIDER_SetValue(hItem, MasterLight_R_slider);
			
			hItem = WM_GetDialogItem(HWIN, ID_SLIDER_1);
			SLIDER_SetValue(hItem, MasterLight_G_slider);
			
			hItem = WM_GetDialogItem(HWIN, ID_SLIDER_2);
			SLIDER_SetValue(hItem, MasterLight_B_slider);
			
			hItem = WM_GetDialogItem(HWIN, ID_BUTTON_0);
			// 格式化字符串并设置文本
			if(MasterLight_R_slider || MasterLight_G_slider || MasterLight_B_slider){
				status = 1;
				BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
			}else{
				status = 0;
				BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOff);
			}
			// 强制刷新控件
			WM_InvalidateWindow(hItem);
			MasterLight_RGBchanged = 0;
		}
		
        // 延时200ms
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
static void DeleteUpdateTask(void) {
    if (xUpdateTaskHandle != NULL) {
        vTaskDelete(xUpdateTaskHandle);
        xUpdateTaskHandle = NULL;
    }
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LightingMaster'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //TEXT_SetText(hItem, "LightingMaster");
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "主灯");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //WM_InvalidateWindow(hItem);  // 强制刷新窗口
    // USER START (Optionally insert additional code for further widget initialization)
	// 根据空间ID,获取空间句柄
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_LightingMaster'
	//
	//BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOff);
	//BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmLightingMasterOn);
    if(status){
        BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
    }else{
        BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmLightingMasterOff);
    }
	// 创建更新任务，传递ID_BUTTON_0控件句柄
    xTaskCreate(UpdateTextTask, "UpdateTextTask", 256, (void*)pMsg->hWin, tskIDLE_PRIORITY + 1, &xUpdateTaskHandle);
	

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    //
	// Initialization of 'Button_MainPage'
	//
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmMainPage);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmMainPagePressed);
	
	//
    // Initialization of 'R'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
	TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    //
    // Initialization of 'G'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
	TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF00));
    //
    // Initialization of 'B'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
	TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetFocusColor(hItem, 0x00043F97);
    SLIDER_SetNumTicks(hItem, 256);
    SLIDER_SetRange(hItem, 0, 255); //[0:255]
    SLIDER_SetValue(hItem, 0);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
    SLIDER_SetFocusColor(hItem, 0x00043F97);
    SLIDER_SetNumTicks(hItem, 256);
    SLIDER_SetRange(hItem, 0, 255); //[0:255]
    SLIDER_SetValue(hItem, 0);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
    SLIDER_SetFocusColor(hItem, 0x00043F97);
    SLIDER_SetNumTicks(hItem, 256);
    SLIDER_SetRange(hItem, 0, 255); //[0:255]
    SLIDER_SetValue(hItem, 0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		status = !status;
        if(status){
            //BUTTON_SetBitmap(pMsg->hWinSrc, BUTTON_BI_UNPRESSED, &bmLightingMasterOn); //替换为使用更新任务更新按钮图片
            //light up
			//HAL_GPIO_WritePin(LED0_GPIO_Port, LED0_Pin, GPIO_PIN_RESET);
			//ESP8266_sendBroadcastCmd("MasterLight_ON&R=255&G=255&B=255");
			MasterLight_R_slider = 255;
			MasterLight_G_slider = 255;
			MasterLight_B_slider = 255;
			sprintf(cmd, "MasterLight_ON&R=%d&G=%d&B=%d", MasterLight_R_slider, MasterLight_G_slider, MasterLight_B_slider);
			//printf("%s", cmd);
			ESP8266_sendBroadcastCmd(cmd);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
			SLIDER_SetValue(hItem, MasterLight_R_slider);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
			SLIDER_SetValue(hItem, MasterLight_G_slider);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
			SLIDER_SetValue(hItem, MasterLight_B_slider);
			
        }else{
            //BUTTON_SetBitmap(pMsg->hWinSrc, BUTTON_BI_UNPRESSED, &bmLightingMasterOff); //替换为使用更新任务更新按钮图片
            //light off
			MasterLight_R_slider = 0;
			MasterLight_G_slider = 0;
			MasterLight_B_slider = 0;
			
			
			//HAL_GPIO_WritePin(LED0_GPIO_Port, LED0_Pin, GPIO_PIN_SET);
			ESP8266_sendBroadcastCmd("MasterLight_OFF");
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
			SLIDER_SetValue(hItem, MasterLight_R_slider);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
			SLIDER_SetValue(hItem, MasterLight_G_slider);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
			SLIDER_SetValue(hItem, MasterLight_B_slider);
        }
		MasterLight_RGBchanged = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //返回主页
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	  	currentDialog = 1;
        hWin1 = CreateWindow0Main(); // 创建WindowMain界面，调用其它界面的Create方法
	  	//销毁任务
		DeleteUpdateTask();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		//printf("clicked\n");
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//printf("released\n");
	  /*
		//这种方式会导致程序奔溃
		if(MasterLight_R_slider){
			status = 1;
			BUTTON_SetBitmap(pMsg->hWinSrc, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
		}
	  */
		sprintf(cmd, "MasterLight_ON&R=%d&G=%d&B=%d", MasterLight_R_slider, MasterLight_G_slider, MasterLight_B_slider);
		//printf("%s\n", cmd);
		ESP8266_sendBroadcastCmd(cmd);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		//printf("value changed\n");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		MasterLight_R_slider = SLIDER_GetValue(hItem);
		MasterLight_RGBchanged = 1;
		//printf("%d\n", MasterLight_R_slider);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_SLIDER_1: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  /*
		if(MasterLight_G_slider){
			status = 1;
			BUTTON_SetBitmap(pMsg->hWinSrc, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
		}
	  */
		sprintf(cmd, "MasterLight_ON&R=%d&G=%d&B=%d", MasterLight_R_slider, MasterLight_G_slider, MasterLight_B_slider);
		ESP8266_sendBroadcastCmd(cmd);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
		MasterLight_G_slider = SLIDER_GetValue(hItem);
		MasterLight_RGBchanged = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_SLIDER_2: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  /*
	  	if(MasterLight_B_slider){
			status = 1;
			BUTTON_SetBitmap(pMsg->hWinSrc, BUTTON_BI_UNPRESSED, &bmLightingMasterOn);
		}
	  */
		sprintf(cmd, "MasterLight_ON&R=%d&G=%d&B=%d", MasterLight_R_slider, MasterLight_G_slider, MasterLight_B_slider);
		ESP8266_sendBroadcastCmd(cmd);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
		MasterLight_B_slider = SLIDER_GetValue(hItem);
		MasterLight_RGBchanged = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
  }
  break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLightingMaster
*/
WM_HWIN CreateLightingMaster(void);
WM_HWIN CreateLightingMaster(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
