/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
#include "esp8266_web.h"  //ip_address
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0  (GUI_ID_USER + 0x02)
#define ID_TEXT_1  (GUI_ID_USER + 0x03)
#define ID_TEXT_2  (GUI_ID_USER + 0x08)
#define ID_TEXT_3  (GUI_ID_USER + 0x0B)
#define ID_TEXT_4  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0  (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPage;
extern GUI_CONST_STORAGE GUI_BITMAP bmMainPagePressed;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "network", ID_TEXT_0, 0, 0, 800, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP:", ID_TEXT_1, 230, 160, 100, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP:", ID_TEXT_2, 230, 230, 100, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text3", ID_TEXT_3, 330, 160, 200, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text4", ID_TEXT_4, 330, 230, 200, 32, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 526, 129, 150, 150, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    //
    // Initialization of 'network'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "网络信息");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'IP:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
  	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "无线");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'IP:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "有线");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetText(hItem, ip_address);  //无线网络ip
	
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //
	// Initialization of 'Button_MainPage'
	//
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmMainPage);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmMainPagePressed);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  	//返回主页
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	    currentDialog = 2;
        hWin2 = CreateWindow1Main(); // 创建WindowMain界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateNetworkInfoWindow(void);
WM_HWIN CreateNetworkInfoWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
