/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include_dlg.h"
#include "esp8266_web.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0            (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0            (GUI_ID_USER + 0x03)
#define ID_TEXT_0            (GUI_ID_USER + 0x05)
#define ID_TEXT_1            (GUI_ID_USER + 0x06)
#define ID_TEXT_2            (GUI_ID_USER + 0x07)
#define ID_TEXT_3            (GUI_ID_USER + 0x08)
#define ID_TEXT_4            (GUI_ID_USER + 0x09)
#define ID_EDIT_0            (GUI_ID_USER + 0x0A)
#define ID_TEXT_5            (GUI_ID_USER + 0x0B)
#define ID_BUTTON_0            (GUI_ID_USER + 0x0C)
#define ID_BUTTON_1            (GUI_ID_USER + 0x0D)
#define ID_TEXT_6            (GUI_ID_USER + 0x0E)
#define ID_TEXT_7            (GUI_ID_USER + 0x0F)
#define ID_TEXT_8            (GUI_ID_USER + 0x10)


// USER START (Optionally insert additional defines)
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 15, 150, 380, 280, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "network", ID_TEXT_0, 0, 0, 800, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP:", ID_TEXT_1, 420, 300, 100, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WIFI:", ID_TEXT_2, 420, 100, 80, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NAME", ID_TEXT_3, 520, 100, 250, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PWD:", ID_TEXT_4, 420, 150, 80, 32, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 520, 150, 250, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "IP:", ID_TEXT_5, 420, 350, 100, 32, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RETURN", ID_BUTTON_0, 600, 200, 140, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONNECT", ID_BUTTON_1, 426, 200, 140, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text6", ID_TEXT_6, 520, 300, 200, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text7", ID_TEXT_7, 520, 350, 200, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WIFI LIST", ID_TEXT_8, 15, 110, 380, 32, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00973F04));
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Item 0");
    LISTBOX_AddString(hItem, "Item 1");
    LISTBOX_AddString(hItem, "Item 2");
    //
    // Initialization of 'network'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "网络");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'IP:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "有线");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'WIFI:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "名称");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'NAME'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);

    //
    // Initialization of 'PWD:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "密码");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    //
    // Initialization of 'IP:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "无线");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetText(hItem, ip_address);  //无线网络ip
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'WIFI LIST'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "无线网络列表");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "连接");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    //TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
	TEXT_SetFont(hItem, &GUI_Fontfont);  // 设置字体
    TEXT_SetText(hItem, "返回");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);  // 设置文本对齐方式（可选）
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'RETURN'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//返回主页
        GUI_EndDialog(pMsg->hWin, 0);  //结束对话框
	    currentDialog = 2;
        hWin2 = CreateWindow1Main(); // 创建WindowMain界面，调用其它界面的Create方法
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'CONNECT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateNetworkWindow(void);
WM_HWIN CreateNetworkWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
