/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: font.c                                                *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\font.txt         *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\font.txt         *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontfont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontfont_4E3B[128] = { /* code 4E3B */
  ________,________,________,________,
  ________,________,________,________,
  ________,____X___,________,________,
  ________,_____XX_,________,________,
  ________,______XX,________,________,
  ________,_______X,X_______,________,
  ________,_______X,XX______,________,
  ________,________,X_______,__X_____,
  ________,________,X_______,_XXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X______X,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  ______X_,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,___X____,
  ________,_______X,X_______,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_4EAE[128] = { /* code 4EAE */
  ________,________,________,________,
  ________,________,________,________,
  ________,_____XX_,________,________,
  ________,______XX,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,__XX____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,X_______,______X_,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______X_,________,
  ________,XX______,______X_,________,
  ________,XX______,______X_,________,
  ________,XXXXXXXX,XXXXXXX_,________,
  ________,XX______,______X_,________,
  ________,________,________,________,
  ____X___,________,________,___X____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,________,___XXX__,
  ___XX___,________,________,__X_____,
  __XXX___,__X_____,________,_X______,
  ________,__XXXXXX,XXXXXX__,________,
  ________,__XX____,___XX___,________,
  ________,__XX____,___XX___,________,
  ________,__XX____,___XX___,________,
  ________,__X_____,___XX___,____X___,
  ________,_XX_____,___XX___,____X___,
  ________,_XX_____,___XX___,____XX__,
  _______X,XX______,___XXX__,___XXXX_,
  _____XXX,________,____XXXX,XXXXXX__,
  __XXX___,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_5C04[128] = { /* code 5C04 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_X______,_______X,________,
  ________,_XX_____,________,XX______,
  ________,_X______,________,X_______,
  ________,X____X__,________,X_______,
  _____XXX,XXXXXXX_,________,X_______,
  _____XX_,_____X__,________,X_______,
  _____XX_,_____X__,________,X_______,
  _____XX_,_____X__,________,X_______,
  _____XX_,_____X__,________,X__XX___,
  _____XXX,XXXXXX_X,XXXXXXXX,XXXXXX__,
  _____XX_,_____X__,________,X_______,
  _____XX_,_____X__,________,X_______,
  _____XX_,_____X__,________,X_______,
  _____XXX,XXXXXX__,________,X_______,
  _____XX_,_____X__,_XX_____,X_______,
  _____XX_,_____X__,__XX____,X_______,
  _____XX_,_____X__,__XXX___,X_______,
  _XXXXXXX,XXXXXX__,__XXX___,X_______,
  ________,_XX__X__,___X____,X_______,
  ________,_XX__X__,________,X_______,
  ________,XX___X__,________,X_______,
  _______X,X____X__,________,X_______,
  _______X,X____X__,________,X_______,
  ______XX,_____X__,________,X_______,
  _____XX_,_____X__,________,X_______,
  ____X___,_____X__,________,X_______,
  ___X____,_XXXXX__,___XXXXX,X_______,
  __X_____,___XXX__,_____XXX,X_______,
  ________,____X___,______XX,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_5C4F[128] = { /* code 5C4F */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,__X_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,________,________,__XX____,
  ______XX,________,________,__XX____,
  ______XX,________,________,__XX____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______X_,________,________,__XX____,
  ______X_,_____X__,______X_,________,
  ______X_,_____XX_,_____XXX,________,
  ______X_,______XX,_____XX_,________,
  ______X_,______XX,_____X__,________,
  ______X_,_______X,____X___,_XX_____,
  ______X_,_XXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,______X_,_____XX_,________,
  _____XX_,______X_,_____XX_,________,
  _____XX_,______X_,_____XX_,________,
  _____XX_,______X_,_____XX_,________,
  _____XX_,______X_,_____XX_,__XX____,
  _____X_X,XXXXXXXX,XXXXXXXX,XXXXX___,
  _____X__,______X_,_____XX_,________,
  ____XX__,______X_,_____XX_,________,
  ____X___,_____XX_,_____XX_,________,
  ____X___,_____XX_,_____XX_,________,
  ___X____,____XX__,_____XX_,________,
  ___X____,____X___,_____XX_,________,
  __X_____,__XX____,_____XX_,________,
  __X_____,_XX_____,_____XX_,________,
  _______X,X_______,_____X__,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_5EA6[128] = { /* code 5EA6 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,________,________,
  ________,________,XX______,________,
  ________,________,XXX_____,___X____,
  _____X__,________,_X______,__XXX___,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,_____X__,_____X__,________,
  _____XX_,_____XXX,_____XXX,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,__XX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XXX,XXXXXXX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____X__,________,_______X,________,
  _____X__,__XXXXXX,XXXXXXXX,X_______,
  ____XX__,_____X__,______XX,X_______,
  ____XX__,______X_,_____XXX,________,
  ____XX__,______XX,_____XX_,________,
  ____X___,_______X,____XX__,________,
  ____X___,________,XX_XX___,________,
  ___XX___,________,_XXX____,________,
  ___X____,________,XXXXX___,________,
  ___X____,______XX,X__XXXX_,________,
  __X_____,____XXX_,_____XXX,XXXXX___,
  __X_____,_XXX____,________,XXXXX___,
  _X___XXX,X_______,________,___X____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_606F[128] = { /* code 606F */
  ________,________,________,________,
  ________,________,________,________,
  ________,______X_,________,________,
  ________,______XX,________,________,
  ________,_____X__,_______X,________,
  ________,XXXXXXXX,XXXXXXXX,XX______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,_______X,X_______,
  ________,______XX,________,________,
  ________,__X____X,XX______,________,
  ________,__XXX___,XX______,________,
  ______X_,__XX____,_X____X_,_XX_____,
  _____XX_,__XX____,______X_,__XXX___,
  _____XX_,__XX____,______X_,___XX___,
  ____XX__,__XX____,______X_,___XXX__,
  ___XXX__,__XX____,______XX,____X___,
  ________,__XXXXXX,XXXXXXXX,________,
  ________,___XXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_6247[128] = { /* code 6247 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,________,________,
  ________,_______X,X_______,________,
  ________,________,XX______,________,
  ______X_,________,X_______,_X______,
  ______XX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,________,________,_XX_____,
  ______XX,________,________,_XX_____,
  ______XX,________,________,_XX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,________,________,_XX_____,
  ______XX,________,________,________,
  ______XX,_______X,________,__X_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,_______X,X_______,__X_____,
  ______XX,_______X,X_______,__X_____,
  ______X_,__X____X,X___X___,__X_____,
  ______X_,__XX___X,X___XXX_,__X_____,
  _____XX_,___XX__X,X____XX_,__X_____,
  _____XX_,___X___X,X____XX_,__X_____,
  _____XX_,_______X,X_______,_XX_____,
  _____X__,_____XXX,X______X,X_X_____,
  _____X__,___XX__X,X____XX_,__X_____,
  ____XX__,_XXX___X,XXXXXX__,__X_____,
  ____X__X,XX_____X,X_XX____,__X_____,
  ___XX___,X______X,X_______,__X_____,
  ___X____,_______X,X_______,__X_____,
  ___X____,___XXXXX,X_____XX,XXX_____,
  __X_____,_____XXX,________,XXX_____,
  _X______,______X_,________,_X______,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_62A5[128] = { /* code 62A5 */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,________,________,
  _______X,XX_____X,XXXXXXXX,XX______,
  _______X,X______X,X_______,XX______,
  _______X,X______X,X_______,XX______,
  _______X,X______X,X_______,XX______,
  _______X,X______X,X_______,XX______,
  _______X,X__XX__X,X_______,XX______,
  _XXXXXXX,XXXXXX_X,X_______,XX______,
  _______X,X______X,X___XXXX,X_______,
  _______X,X______X,X_____XX,X_______,
  _______X,X______X,X_______,________,
  _______X,X______X,X_______,__X_____,
  _______X,X___XX_X,XXXXXXXX,XXXX____,
  _______X,XXXX___X,X_X_____,_XX_____,
  ______XX,XX_____X,X_X_____,_X______,
  ____XXXX,X______X,X__X____,XX______,
  __XXXX_X,X______X,X__X____,XX______,
  __XX___X,X______X,X___X__X,X_______,
  _______X,X______X,X___X__X,X_______,
  _______X,X______X,X____XXX,________,
  _______X,X______X,X____XX_,________,
  _______X,X______X,X____XXX,________,
  _______X,X______X,X___XX_X,X_______,
  _______X,X______X,X__XX___,XXX_____,
  _______X,X______X,X_XX____,_XXXX___,
  _______X,X______X,XX______,__XXXX__,
  ___XXXXX,X______X,X_______,________,
  _____XXX,_______X,X_______,________,
  ______X_,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_6E29[128] = { /* code 6E29 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XX__,____X___,________,X_______,
  _____XX_,____XXXX,XXXXXXXX,XX______,
  ______XX,____XX__,________,X_______,
  ______XX,____XX__,________,X_______,
  ________,__X_XX__,________,X_______,
  ________,_X__XX__,________,X_______,
  ________,_X__XXXX,XXXXXXXX,X_______,
  ________,_X__XX__,________,X_______,
  __XX____,_X__XX__,________,X_______,
  ___XX___,X___XX__,________,X_______,
  ____XX__,X___XX__,________,X_______,
  ____X___,X___XXXX,XXXXXXXX,X_______,
  _______X,____XX__,________,X_______,
  _______X,____X___,________,________,
  _______X,________,________,________,
  ______XX,__X_____,________,__X_____,
  ______X_,__XXXXXX,XXXXXXXX,XXXX____,
  ______X_,__XX___X,X___XX__,_XX_____,
  _____XX_,__XX___X,X___XX__,_XX_____,
  __XXXXX_,__XX___X,X___XX__,_XX_____,
  ____XXX_,__XX___X,X___XX__,_XX_____,
  ____XX__,__XX___X,X___XX__,_XX_____,
  ____XX__,__XX___X,X___XX__,_XX_____,
  ____XX__,__XX___X,X___XX__,_XX_____,
  ____XX__,__XX___X,X___XX__,_XX_____,
  ____XX__,__XX___X,X___XX__,_XX_XX__,
  ____XX_X,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_6E7F[128] = { /* code 6E7F */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____X___,____X___,________,________,
  _____XX_,____XXXX,XXXXXXXX,XXX_____,
  _____XXX,____XX__,________,_XX_____,
  ______XX,____XX__,________,_XX_____,
  ______XX,____XX__,________,_XX_____,
  ________,__X_XX__,________,_XX_____,
  ________,_X__XXXX,XXXXXXXX,XXX_____,
  _XX_____,_X__XX__,________,_XX_____,
  __XX____,_X__XX__,________,_XX_____,
  ___XXX__,X___XX__,________,_XX_____,
  ____XX__,X___XX__,________,_XX_____,
  ____XX__,X___XXXX,XXXXXXXX,XXX_____,
  _______X,____XX__,X____X__,_XX_____,
  _______X,____X___,XX___XX_,________,
  ______XX,________,XX___XX_,________,
  ______X_,________,XX___XX_,___XX___,
  _____XX_,__X_____,XX___XX_,___XXX__,
  _____XX_,___X____,XX___XX_,__XX____,
  _XXXXX__,___XX___,XX___XX_,_XX_____,
  ____XX__,____XX__,XX___XX_,_X______,
  ____XX__,____XX__,XX___XX_,X_______,
  ____XX__,____XX__,XX___XXX,________,
  ____XX__,_____X__,XX___XX_,________,
  ___XXX__,________,XX___XX_,________,
  ___XXX__,________,XX___XX_,________,
  ___XXX__,________,XX___XX_,____X___,
  ____XX__,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_706F[128] = { /* code 706F */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,________,________,
  _______X,X_______,________,________,
  _______X,X_______,________,___XX___,
  _______X,X____XXX,XXXXXXXX,XXXXXX__,
  _______X,X_______,_____XX_,________,
  _______X,X_______,_____XX_,________,
  _______X,X__XX___,_____XX_,________,
  ____X__X,X__XX___,_____XX_,________,
  ____X__X,X_XX____,_____XX_,________,
  ___X___X,XXX_____,_____XX_,________,
  ___X___X,X_______,_____XX_,________,
  __XX___X,X_______,_____XX_,________,
  __XX___X,X_______,_____XX_,________,
  __X____X,X_______,_____XX_,________,
  _______X,X_______,_____XX_,________,
  _______X,X_______,_____XX_,________,
  _______X,X_______,_____XX_,________,
  _______X,________,_____XX_,________,
  _______X,X_______,_____XX_,________,
  ______XX,_XX_____,_____XX_,________,
  ______XX,__XX____,_____XX_,________,
  ______X_,___XX___,_____XX_,________,
  ______X_,___XX___,_____XX_,________,
  _____X__,____X___,_____XX_,________,
  ____XX__,________,_____XX_,________,
  ____X___,_______X,____XX__,________,
  ___X____,________,XXXXXX__,________,
  __X_____,________,__XXXX__,________,
  ________,________,___XX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_8B66[128] = { /* code 8B66 */
  ________,________,________,________,
  ________,________,________,________,
  _______X,____X___,____X___,________,
  _______X,X___XX__,____XX__,________,
  _______X,X___XX__,X___X___,________,
  __XXXXXX,XXXXXXXX,XX_XX___,____X___,
  _____X_X,X___XX__,___XXXXX,XXXXXX__,
  _____XXX,___X___X,___XX___,_X______,
  _____XXX,XXXXXXXX,X_X_X___,XX______,
  ____XX__,___X__XX,__X_X___,XX______,
  ___XX_XX,XXXXX_XX,_X___X_X,X_______,
  ___X__X_,__XX__XX,_____XXX,________,
  ______XX,XXXX__XX,______XX,________,
  ______X_,__XX__X_,_____XXX,X_______,
  ________,______X_,____XX__,XXXX____,
  ________,___XXXX_,__XX____,__XXXX__,
  ________,____XX_X,XX______,____X___,
  ________,________,X_______,___X____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,______X_,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  ________,________,_______X,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  ________,________,________,________,
  ________,________,______X_,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,______XX,________,
  _______X,X_______,______XX,________,
  _______X,XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,______XX,________,
  _______X,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontfont_98CE[128] = { /* code 98CE */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,_______X,________,
  ______XX,XXXXXXXX,XXXXXXXX,X_______,
  ______XX,________,_______X,________,
  ______XX,________,_______X,________,
  ______XX,________,_______X,________,
  ______XX,________,__XX___X,________,
  ______XX,________,__XXX__X,________,
  ______XX,__X_____,_XXX___X,________,
  ______XX,___X____,_XX____X,________,
  ______XX,____X___,_X_____X,________,
  ______XX,_____X__,XX_____X,________,
  ______XX,______X_,X______X,________,
  ______XX,_______X,X______X,________,
  ______XX,______XX,X______X,________,
  ______XX,______X_,XX_____X,________,
  ______X_,_____XX_,_XX____X,X_______,
  ______X_,____XX__,_XXX___X,X_______,
  ______X_,____X___,__XXX__X,X_______,
  _____XX_,___X____,___XX__X,X____X__,
  _____XX_,__X_____,___XX___,X____X__,
  _____X__,_X______,____X___,XX___X__,
  _____X__,X_______,________,XXX__X__,
  ____X__X,________,________,_XX__X__,
  ____X___,________,________,__XXXX__,
  ___X____,________,________,___XXX__,
  __X_____,________,________,____XX__,
  _X______,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontfont_CharInfo[13] = {
   {  32,  32,  4, acGUI_Fontfont_4E3B } /* code 4E3B */
  ,{  32,  32,  4, acGUI_Fontfont_4EAE } /* code 4EAE */
  ,{  32,  32,  4, acGUI_Fontfont_5C04 } /* code 5C04 */
  ,{  32,  32,  4, acGUI_Fontfont_5C4F } /* code 5C4F */
  ,{  32,  32,  4, acGUI_Fontfont_5EA6 } /* code 5EA6 */
  ,{  32,  32,  4, acGUI_Fontfont_606F } /* code 606F */
  ,{  32,  32,  4, acGUI_Fontfont_6247 } /* code 6247 */
  ,{  32,  32,  4, acGUI_Fontfont_62A5 } /* code 62A5 */
  ,{  32,  32,  4, acGUI_Fontfont_6E29 } /* code 6E29 */
  ,{  32,  32,  4, acGUI_Fontfont_6E7F } /* code 6E7F */
  ,{  32,  32,  4, acGUI_Fontfont_706F } /* code 706F */
  ,{  32,  32,  4, acGUI_Fontfont_8B66 } /* code 8B66 */
  ,{  32,  32,  4, acGUI_Fontfont_98CE } /* code 98CE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop13 = {
   0x98CE /* first character */
  ,0x98CE /* last character  */
  ,&GUI_Fontfont_CharInfo[ 12] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop12 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_Fontfont_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontfont_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop11 = {
   0x706F /* first character */
  ,0x706F /* last character  */
  ,&GUI_Fontfont_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontfont_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop10 = {
   0x6E7F /* first character */
  ,0x6E7F /* last character  */
  ,&GUI_Fontfont_CharInfo[  9] /* address of first character */
  ,&GUI_Fontfont_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop9 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontfont_CharInfo[  8] /* address of first character */
  ,&GUI_Fontfont_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop8 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_Fontfont_CharInfo[  7] /* address of first character */
  ,&GUI_Fontfont_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop7 = {
   0x6247 /* first character */
  ,0x6247 /* last character  */
  ,&GUI_Fontfont_CharInfo[  6] /* address of first character */
  ,&GUI_Fontfont_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop6 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_Fontfont_CharInfo[  5] /* address of first character */
  ,&GUI_Fontfont_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop5 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontfont_CharInfo[  4] /* address of first character */
  ,&GUI_Fontfont_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop4 = {
   0x5C4F /* first character */
  ,0x5C4F /* last character  */
  ,&GUI_Fontfont_CharInfo[  3] /* address of first character */
  ,&GUI_Fontfont_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop3 = {
   0x5C04 /* first character */
  ,0x5C04 /* last character  */
  ,&GUI_Fontfont_CharInfo[  2] /* address of first character */
  ,&GUI_Fontfont_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop2 = {
   0x4EAE /* first character */
  ,0x4EAE /* last character  */
  ,&GUI_Fontfont_CharInfo[  1] /* address of first character */
  ,&GUI_Fontfont_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontfont_Prop1 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_Fontfont_CharInfo[  0] /* address of first character */
  ,&GUI_Fontfont_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontfont = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontfont_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

